### ISSUE TITLE
Slack private token in the analysis repo

### ISSUE THREAD

**Issue by jedsalazar** [go-openapi/analysis#82] opened 2022-06-13 19:16 UTC
A slack private token seemingly used for build notifications to a #bots channel has been found in the the analysis repo. It's base64 encoded but should probably be encrypted or set to a variable and the credential should be rotated
https://github.com/cilium/tetragon/blob/main/vendor/github.com/go-openapi/analysis/appveyor.yml#L27-L29

**Comment by vpnachev** [comment] 2023-05-09 06:59
Duplicate of #51

**Comment by casualjim** [comment] 2023-05-10 01:01
It doesn't matter, the chat room is public. Anybody can join, there is nothing there.

**Closed by casualjim** 2023-05-10 01:01 UTC
